/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DoppelbangerEditorBridgeV1Envelope =
  | UiReady
  | ParameterBegin
  | ParameterSet
  | ParameterEnd
  | BypassBegin
  | BypassSet
  | BypassEnd
  | StateSnapshot
  | ParameterChanged
  | BypassChanged
  | CompatibilityError;
export type RequestId = string;
export type ParameterId = number;
export type NormalizedValue = number;

export interface UiReady {
  version: 1;
  type: "ui.ready";
  request_id?: RequestId;
  payload: {};
}
export interface ParameterBegin {
  version: 1;
  type: "parameter.begin_edit";
  request_id?: RequestId;
  payload: {
    id: ParameterId;
  };
}
export interface ParameterSet {
  version: 1;
  type: "parameter.set";
  request_id?: RequestId;
  payload: {
    id: ParameterId;
    value: NormalizedValue;
  };
}
export interface ParameterEnd {
  version: 1;
  type: "parameter.end_edit";
  request_id?: RequestId;
  payload: {
    id: ParameterId;
  };
}
export interface BypassBegin {
  version: 1;
  type: "bypass.begin_edit";
  request_id?: RequestId;
  payload: {};
}
export interface BypassSet {
  version: 1;
  type: "bypass.set";
  request_id?: RequestId;
  payload: {
    value: boolean;
  };
}
export interface BypassEnd {
  version: 1;
  type: "bypass.end_edit";
  request_id?: RequestId;
  payload: {};
}
export interface StateSnapshot {
  version: 1;
  type: "state.snapshot";
  request_id?: RequestId;
  payload: {
    /**
     * @minItems 4
     * @maxItems 4
     */
    parameters: [Parameter, Parameter, Parameter, Parameter];
    bypass: boolean;
    build: string;
    dsp_ready: boolean;
    runtime_mode: "LOCAL";
  };
}
export interface Parameter {
  id: ParameterId;
  normalized: NormalizedValue;
  display: number;
}
export interface ParameterChanged {
  version: 1;
  type: "parameter.changed";
  request_id?: RequestId;
  payload: Parameter;
}
export interface BypassChanged {
  version: 1;
  type: "bypass.changed";
  request_id?: RequestId;
  payload: {
    value: boolean;
  };
}
export interface CompatibilityError {
  version: 1;
  type: "compatibility.error";
  request_id?: RequestId;
  payload: {
    code: string;
  };
}
